### ISSUE TITLE
@conda-forge-admin, please update version

### ISSUE THREAD

**Issue by mlondschien** [conda-forge/ivmodels-feedstock#7]

**Comment by mlondschien** [comment]
@conda-forge/python 
#6 was merged, but https://anaconda.org/conda-forge/ivmodels/files wasn't updated. Any idea what might be the problem?

**Comment by xhochy** [comment]
CI wasn't run on main. Push an empty commit to `main` to retrigger the build.

**Comment by mlondschien** [comment]
This worked. Thanks @xhochy!
